export const bookingItems = [
    {
      "avatar": "https://i.pravatar.cc/5000/1",
      "clientName": "John Doe",
      "clientId": "C001",
      "totalAmount": "$120.00",
      "phoneNumber": "+1-555-0100",
      "email": "john.doe@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-01",
      "bookingID": "B001",
      "notes": "First-time booking."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/2",
      "clientName": "Jane Smith",
      "clientId": "C002",
      "totalAmount": "$150.00",
      "phoneNumber": "+1-555-0101",
      "email": "jane.smith@example.com",
      "status": "active",
      "bookingDate": "2024-09-20",
      "bookingID": "B002",
      "notes": "VIP client."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/3",
      "clientName": "Michael Brown",
      "clientId": "C003",
      "totalAmount": "$80.00",
      "phoneNumber": "+1-555-0102",
      "email": "michael.brown@example.com",
      "status": "done",
      "bookingDate": "2024-08-15",
      "bookingID": "B003",
      "notes": "No special requests."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/4",
      "clientName": "Emily Davis",
      "clientId": "C004",
      "totalAmount": "$200.00",
      "phoneNumber": "+1-555-0103",
      "email": "emily.davis@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-05",
      "bookingID": "B004",
      "notes": "Requires dietary restrictions."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/5",
      "clientName": "Robert Wilson",
      "clientId": "C005",
      "totalAmount": "$90.00",
      "phoneNumber": "+1-555-0104",
      "email": "robert.wilson@example.com",
      "status": "active",
      "bookingDate": "2024-09-25",
      "bookingID": "B005",
      "notes": "Frequent visitor."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/6",
      "clientName": "Olivia Martinez",
      "clientId": "C006",
      "totalAmount": "$75.00",
      "phoneNumber": "+1-555-0105",
      "email": "olivia.martinez@example.com",
      "status": "done",
      "bookingDate": "2024-07-10",
      "bookingID": "B006",
      "notes": "Late arrival expected."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/7",
      "clientName": "Daniel Garcia",
      "clientId": "C007",
      "totalAmount": "$130.00",
      "phoneNumber": "+1-555-0106",
      "email": "daniel.garcia@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-10",
      "bookingID": "B007",
      "notes": "Preferred seating by the window."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/8",
      "clientName": "Sophia Martinez",
      "clientId": "C008",
      "totalAmount": "$160.00",
      "phoneNumber": "+1-555-0107",
      "email": "sophia.martinez@example.com",
      "status": "active",
      "bookingDate": "2024-09-18",
      "bookingID": "B008",
      "notes": "Celebrating anniversary."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/9",
      "clientName": "James Anderson",
      "clientId": "C009",
      "totalAmount": "$85.00",
      "phoneNumber": "+1-555-0108",
      "email": "james.anderson@example.com",
      "status": "done",
      "bookingDate": "2024-08-25",
      "bookingID": "B009",
      "notes": "No special requests."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/10",
      "clientName": "Ava Thomas",
      "clientId": "C010",
      "totalAmount": "$95.00",
      "phoneNumber": "+1-555-0109",
      "email": "ava.thomas@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-15",
      "bookingID": "B010",
      "notes": "Vegetarian meal requested."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/11",
      "clientName": "Liam Wilson",
      "clientId": "C011",
      "totalAmount": "$140.00",
      "phoneNumber": "+1-555-0110",
      "email": "liam.wilson@example.com",
      "status": "active",
      "bookingDate": "2024-09-22",
      "bookingID": "B011",
      "notes": "Requires high chair."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/12",
      "clientName": "Isabella Lee",
      "clientId": "C012",
      "totalAmount": "$120.00",
      "phoneNumber": "+1-555-0111",
      "email": "isabella.lee@example.com",
      "status": "done",
      "bookingDate": "2024-08-30",
      "bookingID": "B012",
      "notes": "Allergy to nuts."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/13",
      "clientName": "Ethan Taylor",
      "clientId": "C013",
      "totalAmount": "$105.00",
      "phoneNumber": "+1-555-0112",
      "email": "ethan.taylor@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-20",
      "bookingID": "B013",
      "notes": "Requires wheelchair access."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/14",
      "clientName": "Mia Johnson",
      "clientId": "C014",
      "totalAmount": "$125.00",
      "phoneNumber": "+1-555-0113",
      "email": "mia.johnson@example.com",
      "status": "active",
      "bookingDate": "2024-09-28",
      "bookingID": "B014",
      "notes": "Birthday celebration."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/15",
      "clientName": "Noah Brown",
      "clientId": "C015",
      "totalAmount": "$135.00",
      "phoneNumber": "+1-555-0114",
      "email": "noah.brown@example.com",
      "status": "done",
      "bookingDate": "2024-07-25",
      "bookingID": "B015",
      "notes": "Table near the bar."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/16",
      "clientName": "Charlotte White",
      "clientId": "C016",
      "totalAmount": "$110.00",
      "phoneNumber": "+1-555-0115",
      "email": "charlotte.white@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-25",
      "bookingID": "B016",
      "notes": "Gluten-free meal required."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/17",
      "clientName": "Benjamin Harris",
      "clientId": "C017",
      "totalAmount": "$140.00",
      "phoneNumber": "+1-555-0116",
      "email": "benjamin.harris@example.com",
      "status": "active",
      "bookingDate": "2024-09-30",
      "bookingID": "B017",
      "notes": "Late arrival expected."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/18",
      "clientName": "Amelia Clark",
      "clientId": "C018",
      "totalAmount": "$90.00",
      "phoneNumber": "+1-555-0117",
      "email": "amelia.clark@example.com",
      "status": "done",
      "bookingDate": "2024-08-10",
      "bookingID": "B018",
      "notes": "No special requests."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/19",
      "clientName": "Jacob Robinson",
      "clientId": "C019",
      "totalAmount": "$160.00",
      "phoneNumber": "+1-555-0118",
      "email": "jacob.robinson@example.com",
      "status": "upcoming",
      "bookingDate": "2024-11-01",
      "bookingID": "B019",
      "notes": "Anniversary dinner."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/20",
      "clientName": "Harper Lewis",
      "clientId": "C020",
      "totalAmount": "$130.00",
      "phoneNumber": "+1-555-0119",
      "email": "harper.lewis@example.com",
      "status": "active",
      "bookingDate": "2024-09-17",
      "bookingID": "B020",
      "notes": "Table near the window."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/21",
      "clientName": "Lily Young",
      "clientId": "C021",
      "totalAmount": "$125.00",
      "phoneNumber": "+1-555-0120",
      "email": "lily.young@example.com",
      "status": "done",
      "bookingDate": "2024-07-20",
      "bookingID": "B021",
      "notes": "Vegetarian option needed."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/22",
      "clientName": "Mason Walker",
      "clientId": "C022",
      "totalAmount": "$115.00",
      "phoneNumber": "+1-555-0121",
      "email": "mason.walker@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-30",
      "bookingID": "B022",
      "notes": "Requires a quiet table."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/23",
      "clientName": "Ella Hall",
      "clientId": "C023",
      "totalAmount": "$140.00",
      "phoneNumber": "+1-555-0122",
      "email": "ella.hall@example.com",
      "status": "active",
      "bookingDate": "2024-09-10",
      "bookingID": "B023",
      "notes": "Birthday party."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/24",
      "clientName": "Logan Allen",
      "clientId": "C024",
      "totalAmount": "$105.00",
      "phoneNumber": "+1-555-0123",
      "email": "logan.allen@example.com",
      "status": "done",
      "bookingDate": "2024-08-05",
      "bookingID": "B024",
      "notes": "Late arrival."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/25",
      "clientName": "Avery King",
      "clientId": "C025",
      "totalAmount": "$90.00",
      "phoneNumber": "+1-555-0124",
      "email": "avery.king@example.com",
      "status": "upcoming",
      "bookingDate": "2024-11-05",
      "bookingID": "B025",
      "notes": "Allergy to shellfish."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/26",
      "clientName": "Eli Scott",
      "clientId": "C026",
      "totalAmount": "$120.00",
      "phoneNumber": "+1-555-0125",
      "email": "eli.scott@example.com",
      "status": "active",
      "bookingDate": "2024-09-15",
      "bookingID": "B026",
      "notes": "Requires high chair."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/27",
      "clientName": "Scarlett Adams",
      "clientId": "C027",
      "totalAmount": "$130.00",
      "phoneNumber": "+1-555-0126",
      "email": "scarlett.adams@example.com",
      "status": "done",
      "bookingDate": "2024-07-15",
      "bookingID": "B027",
      "notes": "No special requests."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/28",
      "clientName": "Jackson Baker",
      "clientId": "C028",
      "totalAmount": "$140.00",
      "phoneNumber": "+1-555-0127",
      "email": "jackson.baker@example.com",
      "status": "upcoming",
      "bookingDate": "2024-10-05",
      "bookingID": "B028",
      "notes": "Gluten-free meal requested."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/29",
      "clientName": "Chloe Nelson",
      "clientId": "C029",
      "totalAmount": "$110.00",
      "phoneNumber": "+1-555-0128",
      "email": "chloe.nelson@example.com",
      "status": "active",
      "bookingDate": "2024-09-12",
      "bookingID": "B029",
      "notes": "Requires wheelchair access."
    },
    {
      "avatar": "https://i.pravatar.cc/5000/30",
      "clientName": "Lucas Carter",
      "clientId": "C030",
      "totalAmount": "$125.00",
      "phoneNumber": "+1-555-0129",
      "email": "lucas.carter@example.com",
      "status": "done",
      "bookingDate": "2024-08-05",
      "bookingID": "B030",
      "notes": "Celebration of graduation."
    }
  ]
  